/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AppleClone(props) {
  const { nodes, materials } = useGLTF(".././models/p2.glb");

  return (
    <group {...props} dispose={null}>
    <mesh
      geometry={nodes['apple-#173'].geometry}
      material={nodes['apple-#173'].material}
    />
  </group>
  );
}

useGLTF.preload(".././models/p2.glb");
