/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Outlines, useGLTF } from "@react-three/drei";

export default function MernEats(props) {
  const { nodes } = useGLTF(".././models/p3.glb");
  const material = useGLTF(".././models/p2.glb").nodes["apple-#173"].material;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={material} />
    </group>
  );
}

useGLTF.preload(".././models/p3.glb");
