/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Amp(props) {
  const { nodes, materials } = useGLTF('./models/amp.glb')
  return (
    <group {...props} dispose={null}>
      <group position={nodes['pCylinder93_sofa1_0002'].position} rotation={nodes['pCylinder93_sofa1_0002'].rotation}>
        <mesh geometry={nodes.pCylinder93_sofa1_0002_1.geometry} material={materials.SVGMat} />
        <mesh
          geometry={nodes.pCylinder93_sofa1_0002_2.geometry}
          material={materials['guitar.001']}
        />
        <mesh
          geometry={nodes.pCylinder93_sofa1_0002_3.geometry}
          material={materials['material_0.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/amp.glb')
