/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mike Inel (https://sketchfab.com/mikeinel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmo-realistic-5d8a3f209118401da46e3b1b38903961
Title: BMO (Realistic)
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations, Bounds } from '@react-three/drei';
import { useEffect } from 'react';
import SelectToZoom from './SelectToZoom';

export default function Bmo(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		'../../models/bmo_realistic/scene.gltf'
	);
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions.Idle.play();
	});

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
			scale={[0.15, 0.15, 0.15]}
			position={[-1.8, 2.3, -4.4]}
			rotation={[0, Math.PI / 1.3, 0]}
		>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					position={[0, 0, 0]}
					rotation={[Math.PI / 2, 0.004, -0.001]}
					scale={0.11}
				>
					<group
						name="fbx_mergefbx"
						rotation={[-Math.PI, 0, 0]}
					>
						<group name="Object_2">
							<group name="RootNode">
								<group
									name="BMO-Root"
									rotation={[Math.PI / 2, 0, 0]}
								>
									<group
										name="BMO-Rig-Body"
										position={[0, 10, 0]}
										rotation={[-Math.PI / 2, 0, 0]}
									>
										<group name="Object_6">
											<primitive object={nodes._rootJoint} />
											<skinnedMesh
												name="Object_22"
												geometry={nodes.Object_22.geometry}
												material={materials.material}
												skeleton={nodes.Object_22.skeleton}
											/>
											<group
												name="BMO-Body"
												rotation={[Math.PI / 2, 0, 0]}
											>
												<Bounds observe margin={3}>
													<SelectToZoom>
														<mesh
															name="BMO-Body_BMO_0"
															geometry={nodes['BMO-Body_BMO_0'].geometry}
															material={materials.material}
														/>
													</SelectToZoom>
												</Bounds>
												<mesh
													name="BMO-Body_BMO-Screen_0"
													geometry={nodes['BMO-Body_BMO-Screen_0'].geometry}
													material={materials['BMO-Screen']}
												/>
											</group>
											<group name="Object_21" />
										</group>
									</group>
									<group
										name="BMO-Skin"
										rotation={[-Math.PI / 2, 0, 0]}
									/>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('../../models/bmo_realistic/scene.gltf');
