/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { FrontSide } from 'three'
import * as THREE from 'three'

export default function Carpet(props) {
  const { nodes, materials } = useGLTF('./models/carpet.glb')
  console.log(nodes);
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.255, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          side={THREE.FrontSide}
          castShadow
          receiveShadow
          geometry={nodes['Carpet1_Material_#26_0'].geometry}
          material={materials.Material_26}
          position={[-0.977, 1.305, 0.026]}
          rotation={[0, 0, 0.561]}
        />
      </group>
    </group>
  )
}


useGLTF.preload('./models/carpet.glb')
