/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GuitarSofa(props) {
  const { nodes, materials } = useGLTF('./models/guitar-sofa.glb')
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model004"
        position={[0, 0.264, -12.841]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.302}>
        <group
          name="d7f8e6cb41fd42f59c3679f3b2a1f309fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
          <group
            name="Guitar_Stand"
            position={[-9.114, -0.846, 84.666]}
            rotation={[-Math.PI / 2, 0, 0.495]}
            scale={100}>
            <mesh
              name="Guitar_Stand_Guitar_Stand_0"
              castShadow
              receiveShadow
              geometry={nodes.Guitar_Stand_Guitar_Stand_0.geometry}
              material={materials.Guitar_Stand}
              position={[-41.969, -29.893, 0.025]}
              rotation={[0, 0, 1.385]}
              scale={3.153}
            />
          </group>
        </group>
      </group>
      <group name="Sketchfab_model005" position={[0, 0.264, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group name="Gibson_A1objcleanergles001" position={[-12.968, -5.228, -39.37]}>
          <mesh
            name="Object_3001"
            castShadow
            receiveShadow
            geometry={nodes.Object_3001.geometry}
            material={materials['Gibson_A1_LOD001_Mat.001']}
            position={[7.399, 3.623, 39.918]}
            rotation={[0.124, -0.376, 1.898]}
            scale={0.047}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model002"
        position={[0, 0.265, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.26}>
        <mesh
          name="Carpet1_Material_#26_0"
          castShadow
          receiveShadow
          geometry={nodes['Carpet1_Material_#26_0'].geometry}
          material={materials.Material_26}
          position={[-3.75, 5.011, 0.1]}
          rotation={[0, 0, 0.561]}
          scale={0.877}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/guitar-sofa.glb')
