/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Guitar(props) {
  const { nodes, materials } = useGLTF('/guitar-v2.glb')
  return (
    <group position={[-6.5,0,1.5]} rotation={[0, Math.PI/2, 0]} scale={0.35} {...props} dispose={null}>
      <group position={[0, 0, -12.841]} rotation={[-Math.PI / 2, 0, 0]} scale={0.302}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-9.114, -0.846, 84.667]}
            rotation={[-Math.PI / 2, 0, 0.495]}
            scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Guitar_Stand_Guitar_Stand_0.geometry}
              material={materials.Guitar_Stand}
              position={[-18.698, -34.652, 0]}
              rotation={[0, 0, -0.49]}
              scale={10}
            />
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-12.968, -5.228, -39.37]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3001.geometry}
            material={materials['Gibson_A1_LOD001_Mat.001']}
            position={[11.031, 2.081, 41.089]}
            rotation={[-0.395, 0, 0]}
            scale={0.15}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/guitar-v2.glb')
