/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Laptop(props) {
	const { nodes, materials } = useGLTF('./models/laptop.glb');
	return (
		<group
			{...props}
			dispose={null}
		>
			<group
				rotation={nodes.laptop.rotation}
				scale={nodes.laptop.scale}
				position={nodes.laptop.position}
			>
				<mesh
					geometry={nodes.Base_grey_cover_0002.geometry}
					material={materials['grey_cover.002']}
				/>
				<mesh
					geometry={nodes.Base_grey_cover_0002_1.geometry}
					material={materials['black.002']}
				/>
				<mesh
					geometry={nodes.Base_grey_cover_0002_2.geometry}
					material={materials['grey_darker.002']}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('./models/laptop.glb');
