/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Laptop(props) {
  const { nodes, materials } = useGLTF('./models/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.34186137, 2.31492853, -5.63775015]}
        rotation={[-Math.PI, 1.31913011, -Math.PI]}
        scale={[0.34308976, 0.3430897, 0.34308976]}>
        <mesh geometry={nodes.Object_0006.geometry} material={materials['case']} />
        <mesh geometry={nodes.Object_0006_1.geometry} material={materials.slots_1} />
        <mesh geometry={nodes.Object_0006_2.geometry} material={materials.speaker} />
        <mesh geometry={nodes.Object_0006_3.geometry} material={materials.bezel} />
        <mesh geometry={nodes.Object_0006_4.geometry} material={materials.slots_2} />
        <mesh geometry={nodes.Object_0006_5.geometry} material={materials.shiny_parts} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/laptop.glb')
