/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import LaptopScreen from "./LaptopScreen";

const Laptop = React.forwardRef(({ isAbout }, ref) => {
  const { nodes, materials } = useGLTF("./models/laptop.glb");
  return (
    <group dispose={null}>
      <group
        position={[-1.477, 2.41, -5.561]}
        rotation={[-Math.PI / 2, 0, 1.829]}
        scale={3.241}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[1.859, 0.384, -4.797]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Base_grey_cover_0_1.geometry}
              material={materials.grey_cover}
            />
            <mesh
              geometry={nodes.Base_grey_cover_0_2.geometry}
              material={materials.black}
            />
            <mesh
              geometry={nodes.Base_grey_cover_0_3.geometry}
              material={materials.grey_darker}
            />
          </group>
        </group>
      </group>
      <LaptopScreen isAbout={isAbout} />
    </group>
  );
})

export default Laptop;
useGLTF.preload("./models/laptop.glb");
