/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'

export default function LaptopScreen(props) {
  const { nodes, materials } = useGLTF('./models/laptopScreen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.laptopScreen.geometry}
        material={nodes.laptopScreen.material}
        position={[-1.805, 2.758, -5.52]}
        rotation={[-Math.PI, 1.319, -Math.PI]}
        scale={0.343}
      >
        <Html position-z={0.01} occlude rotation={[-Math.PI / 18,0,0]} transform>
          <div>Test</div>
        </Html>
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/laptopScreen.glb')
