/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Logos(props) {
  const { nodes, materials } = useGLTF('./models/logos-book.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface941_guitar_0.geometry}
        material={materials.guitar}
        position={[-5.718, 0.378, 0.438]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface941_white_0.geometry}
        material={materials.white}
        position={[-5.718, 0.378, 0.438]}
      />
      <group position={[-5.573, 2.63, -7.695]} rotation={[1.274, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[-5.522, 2.342, -6.772]} rotation={[0, -0.502, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve011.geometry}
          material={materials.white2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve011_1.geometry}
          material={materials.blue}
        />
      </group>
      <group position={[-7.726, 2.366, -6.524]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve014.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve014_1.geometry}
          material={materials['Material.007']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nodejs.geometry}
        material={materials.flower}
        position={[-6.282, 2.655, -7.147]}
        rotation={[1.055, -0.096, -1.404]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.threejs.geometry}
        material={materials['material_0.001']}
        position={[-7.444, 2.903, -6.375]}
        rotation={[0, 0.253, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.react001.geometry}
        material={materials.blue}
        position={[-5.206, 2.506, -7.076]}
        scale={3.944}
      />
    </group>
  )
}

useGLTF.preload('./models/logos-book.glb')


