/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function wallLight(props) {
  const { nodes, materials } = useGLTF('./models/wallLight.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gold_lambert3_0.geometry}
        material={materials.lambert3}
        position={[-7.051, 4.504, -0.985]}
        rotation={[0, 1.571, 0]}
      />
    </group>
  )
}

useGLTF.preload('./models/wallLight.glb')
