/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import Annotation from './Annotation';

export default function wallLight(props) {
	const { nodes, materials } = useGLTF('./models/wallLight.glb');
	return (
		<>
      <Annotation distanceFactor={9} position={[-7,6,-1.7]} selected={4} title={'Projects'} />
			<group
				{...props}
				dispose={null}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.gold_lambert3_0.geometry}
					material={materials.lambert3}
					position={nodes.gold_lambert3_0.position}
					rotation={nodes.gold_lambert3_0.rotation}
				/>
			</group>
		</>
	);
}

useGLTF.preload('./models/wallLight.glb');
